<a href="https://colab.research.google.com/github/MadanaBalaHarini/Fundamental/blob/main/hand_digit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/s.csv")

In [ ]:
data

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [ ]:
data.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [ ]:
data.tail()

ImageId  Label
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

In [ ]:
data.isna()

ImageId  Label
0        False  False
1        False  False
2        False  False
3        False  False
4        False  False
...        ...    ...
27995    False  False
27996    False  False
27997    False  False
27998    False  False
27999    False  False

[28000 rows x 2 columns]

In [ ]:
data.isna().sum()

ImageId    0
Label      0
dtype: int64

In [ ]:
data.describe()

ImageId         Label
count  28000.000000  28000.000000
mean   14000.500000      4.448179
std     8083.048105      2.895990
min        1.000000      0.000000
25%     7000.750000      2.000000
50%    14000.500000      4.000000
75%    21000.250000      7.000000
max    28000.000000      9.000000

In [ ]:
x=data['ImageId'].values.reshape(-1,1)
y=data['Label']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
from sklearn.svm import SVC
lr=SVC()

In [ ]:
model=lr.fit(x_train,y_train)

pre=model.predict(x_test)
print(pre)

[1 1 1 ... 1 1 1]


In [21]:
import sklearn
from sklearn.metrics import confusion_matrix, classification_report
print(sklearn.metrics.confusion_matrix(y_test,pre))
print (sklearn.metrics.classification_report(y_test, pre))

[[  0 692   0   0   0   0   0   0   0   0]
 [  0 802   0   0   0   0   0   0   0   0]
 [  0 725   0   0   0   0   0   0   0   0]
 [  0 660   0   0   0   0   0   0   0   0]
 [  0 693   0   0   0   0   0   0   0   0]
 [  0 636   0   0   0   0   0   0   0   0]
 [  0 687   0   0   0   0   0   0   0   0]
 [  0 707   0   0   0   0   0   0   0   0]
 [  0 691   0   0   0   0   0   0   0   0]
 [  0 707   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       692
           1       0.11      1.00      0.21       802
           2       0.00      0.00      0.00       725
           3       0.00      0.00      0.00       660
           4       0.00      0.00      0.00       693
           5       0.00      0.00      0.00       636
           6       0.00      0.00      0.00       687
           7       0.00      0.00      0.00       707
           8       0.00      0.00      0.00       691
           9       0.00     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
