<a href="https://colab.research.google.com/github/MadanaBalaHarini/Fundamental/blob/main/MovieRecommendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/drive/MyDrive/Dataset.csv")

In [3]:
data

user_id  item_id  rating  timestamp
0             0       50       5  881250949
1             0      172       5  881250949
2             0      133       1  881250949
3           196      242       3  881250949
4           186      302       3  891717742
...         ...      ...     ...        ...
99998       880      476       3  880175444
99999       716      204       5  879795543
100000      276     1090       1  874795795
100001       13      225       2  882399156
100002       12      203       3  879959583

[100003 rows x 4 columns]

In [4]:
data.head()

user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [5]:
data.tail()

user_id  item_id  rating  timestamp
99998       880      476       3  880175444
99999       716      204       5  879795543
100000      276     1090       1  874795795
100001       13      225       2  882399156
100002       12      203       3  879959583

In [6]:
data.describe()

user_id        item_id         rating     timestamp
count  100003.000000  100003.000000  100003.000000  1.000030e+05
mean      462.470876     425.520914       3.529864  8.835288e+08
std       266.622454     330.797791       1.125704  5.343791e+06
min         0.000000       1.000000       1.000000  8.747247e+08
25%       254.000000     175.000000       3.000000  8.794487e+08
50%       447.000000     322.000000       4.000000  8.828269e+08
75%       682.000000     631.000000       4.000000  8.882600e+08
max       943.000000    1682.000000       5.000000  8.932866e+08

In [7]:
data.isnull()

user_id  item_id  rating  timestamp
0         False    False   False      False
1         False    False   False      False
2         False    False   False      False
3         False    False   False      False
4         False    False   False      False
...         ...      ...     ...        ...
99998     False    False   False      False
99999     False    False   False      False
100000    False    False   False      False
100001    False    False   False      False
100002    False    False   False      False

[100003 rows x 4 columns]

In [8]:
data.isna().sum()

user_id      0
item_id      0
rating       0
timestamp    0
dtype: int64

In [9]:
data.drop_duplicates()

user_id  item_id  rating  timestamp
0             0       50       5  881250949
1             0      172       5  881250949
2             0      133       1  881250949
3           196      242       3  881250949
4           186      302       3  891717742
...         ...      ...     ...        ...
99998       880      476       3  880175444
99999       716      204       5  879795543
100000      276     1090       1  874795795
100001       13      225       2  882399156
100002       12      203       3  879959583

[100003 rows x 4 columns]

In [12]:
x=data['item_id'].values.reshape(-1,1)
y=data['rating']

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [14]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()


In [15]:
model=lr.fit(x_train,y_train)

pre=model.predict(x_test)
print(pre)


[4 4 4 ... 4 4 4]


In [17]:
from sklearn.metrics import confusion_matrix
a=confusion_matrix(pre,y_test)
print(a)

[[   0    0    0    0    0]
 [   0    0    0    0    0]
 [ 423  641 1107  953  419]
 [1092 2220 5662 7597 4887]
 [   0    0    0    0    0]]
